CREATE EXTERNAL TABLE IF NOT EXISTS EMPLOYEE_EXT (name String, eid INT,deptid INT, salary String, type String, joindate date)
COMMENT 'Employee Contract details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INPATH '/mnt/c/Users/Miles/Downloads/13a6c913-2a63-4a0c-9a34-fe2035f16c6bynts0/employee_contract.txt' OVERWRITE INTO TABLE EMPLOYEE_EXT;

SELECT * FROM EMPLOYEE_EXT;


SELECT *, AVG(salary) OVER (PARTITION BY deptid ORDER BY joindate) FROM EMPLOYEE_EXT;
SELECT *, MAX(salary) OVER (PARTITION BY deptid ORDER BY joindate) FROM EMPLOYEE_EXT;
SELECT *, AVG(salary) OVER (PARTITION BY deptid ORDER BY joindate ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) 
FROM EMPLOYEE_EXT;